name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Build and push the Docker image
      env:
        BOX_VERSION: 1.36.0
        KUBECTL_VERSION: v1.25.7
      run: |
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl 
        docker build . --file Dockerfile --build-arg KUBECTL_VERSION=$KUBECTL_VERSION --build-arg BOX_VERSION=$BOX_VERSION --tag box-kubectl:$KUBECTL_VERSION
        docker tag box-kubectl:$KUBECTL_VERSION silententity/box-kubectl:$KUBECTL_VERSION
        docker push silententity/box-kubectl:$KUBECTL_VERSION
